import Stripe from 'stripe';

const secretKey = process.env.STRIPE_SECRET_KEY || 'sk_test_mock';

export const stripe = new Stripe(secretKey, {
  apiVersion: '2025-02-24.acacia',
  typescript: true,
});

export const PLANS = {
  STARTER: {
    name: "Starter (14 jours d'essai gratuit)",
    priceMonthly: 29,
    priceAnnualMonthly: 23,
    priceAnnualTotal: 276, // 1 seul paiement annuel de 276 € (23 € x 12)
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID || 'price_starter_29',
    priceIdAnnual: process.env.NEXT_PUBLIC_STRIPE_STARTER_ANNUAL_PRICE_ID || 'price_starter_annual_276',
    priceId: process.env.NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID || 'price_starter_29',
    maxFolderRequests: 10,
    maxUsers: 1,
    storageLimit: '5 Go',
    hasAutoReminders: false,
    hasCustomBranding: false,
    hasAiVerification: false,
    trialDays: 14,
    features: [
      'Jusqu\'à 10 Portails de Collecte Client actifs / mois',
      '1 Utilisateur unique inclus',
      '5 Go de stockage sécurisé souverain',
      'Relances manuelles en 1-clic par e-mail',
      'Lien unique de dépôt mobile sans création de compte',
      'Exportation ZIP 1-clic des justificatifs',
    ],
  },
  PRO: {
    name: 'Pro Illimité',
    priceMonthly: 79,
    priceAnnualMonthly: 63,
    priceAnnualTotal: 756, // 1 seul paiement annuel de 756 € (63 € x 12)
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID || 'price_pro_79',
    priceIdAnnual: process.env.NEXT_PUBLIC_STRIPE_PRO_ANNUAL_PRICE_ID || 'price_pro_annual_756',
    priceId: process.env.NEXT_PUBLIC_STRIPE_PRO_PRICE_ID || 'price_pro_79',
    maxFolderRequests: Infinity,
    maxUsers: 5,
    storageLimit: '500 Go',
    hasAutoReminders: true,
    hasCustomBranding: true,
    hasAiVerification: false,
    trialDays: 0,
    features: [
      'Portails de Collecte Client ILLIMITÉS',
      '5 Utilisateurs collaborateurs inclus',
      '500 Go de stockage cloud sécurisé',
      'Relances automatiques quotidiennes par e-mail',
      'Logo personnalisé (téléversement PNG/SVG & lien)',
      'Marque blanche & personnalisation des thèmes',
      'Exports ZIP groupés avec dossiers structurés',
      'Support client prioritaire 7j/7',
    ],
  },
  AGENCY_SCALE: {
    name: 'Agence Scale (Forfait Ultime Agences)',
    priceMonthly: 247,
    priceAnnualMonthly: 230,
    priceAnnualTotal: 2760, // 1 seul paiement annuel de 2 760 € (230 € x 12)
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_SCALE_PRICE_ID || 'price_scale_247',
    priceIdAnnual: process.env.NEXT_PUBLIC_STRIPE_SCALE_ANNUAL_PRICE_ID || 'price_scale_annual_2760',
    priceId: process.env.NEXT_PUBLIC_STRIPE_SCALE_PRICE_ID || 'price_scale_247',
    maxFolderRequests: Infinity,
    maxUsers: 20,
    storageLimit: '2 To + Google Drive Master',
    hasAutoReminders: true,
    hasCustomBranding: true,
    hasAiVerification: true,
    trialDays: 0,
    features: [
      'Portails de Collecte Client & Contacts ILLIMITÉS (Inclus volume agence 300+)',
      '20 Utilisateurs collaborateurs d\'équipe d\'agence inclus',
      '2 To d\'espace de stockage cloud + Google Drive Master',
      'Intégration EXCLUSIVE Zapier, Make, Notion & API Webhooks HTTP',
      'Toutes les vérifications IA Vision (CNI, Passeports, Paye, Anti-Fraude)',
      'Relances automatiques quotidiennes par e-mail 24/7',
      'Support VIP Prioritaire 24/7 + Chargé de compte dédié',
    ],
  },
  AI_ENTERPRISE: {
    name: 'IA Enterprise',
    priceMonthly: 149,
    priceAnnualMonthly: 119,
    priceAnnualTotal: 1428, // 1 seul paiement annuel de 1428 € (119 € x 12)
    priceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_AI_PRICE_ID || 'price_ai_149',
    priceIdAnnual: process.env.NEXT_PUBLIC_STRIPE_AI_ANNUAL_PRICE_ID || 'price_ai_annual_1428',
    priceId: process.env.NEXT_PUBLIC_STRIPE_AI_PRICE_ID || 'price_ai_149',
    maxFolderRequests: Infinity,
    maxUsers: 10,
    storageLimit: '1 To Cloud Sécurisé',
    hasAutoReminders: true,
    hasCustomBranding: true,
    hasAiVerification: true,
    trialDays: 0,
    features: [
      'Portails & Contacts Client ILLIMITÉS',
      '10 Utilisateurs collaborateurs d\'équipe inclus',
      '1 To d\'espace de stockage cloud sécurisé',
      'Inspection IA des CNI & Passeports (Bandes MRZ ISO 7501)',
      'Contrôle automatique IA de récence des justificatifs (-3 mois)',
      'Détection automatique et extraction des fiches de paie',
      'Score Anti-Fraude & Rapport d\'Audit de sincérité',
      'Support client prioritaire 7j/7',
    ],
  },
};
